Name: <?=$data['name']?>
Business Name: <?=$data['business_name']?>
Address 1: <?=$data['address_1']?>
Address 2: <?=$data['address_2']?>
City: <?=$data['city']?>
State: <?=$data['state']?>
ZIP: <?=$data['zip']?>
Phone: <?=$data['phone']?>
Cell Phone: <?=$data['cell_phone']?>
Email: <?=$data['email']?>
Project Location: <?=$data['project_location']?>
Type of Occupancy: <?=$data['type_of_occupancy']?>
Land and/or Building work Involved: <?=$data['land_and_or_building_work_involved']?>
Permit Status: <?=$data['permit_status']?>
Square Footage: <?=$data['square_footage_of_project']?>
Building Dimensions: <?=$data['building_dimensions_if_known']?>
Type of Exterior Construction: <?=$data['type_of_exterior_construction']?>
Type of Roofing: <?=$data['type_of_roofing']?>
Type of Doors: <?=$data['type_of_doors']?>
Mechanical Work Involved: <?=$data['mechanical_work_involved']?>
